# GitHub Pages configuration
title: "AI-Powered Content Creation Studio"
description: "Create and enhance content using Chrome's built-in AI"
baseurl: "/google-chrome-ai-gemini-nano"
url: "https://google-chrome-ai-gemini-nano.github.io"
theme: jekyll-theme-cayman

